# .readthedocs.yml
# This file is used to configure Read the Docs build.

version: 2

# Define conda environment
# conda:
#   environment: environment.yml



# Build documentation using Sphinx
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    post_install:
    - pip install git+https://github.com/Oucru-Innovations/vital-DSP.git
  #     - python -m virtualenv $READTHEDOCS_VIRTUALENV_PATH
  #     - pip install -r docs/requirements.txt

# Define the Python version and install dependencies
python:
  # Match this with the 'python_requires' in setup.py
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .


# Custom configurations for the documentation builder
formats:
  - pdf
  - epub

# Ensure that the correct index file is referenced
sphinx:
  builder: html
  configuration: docs/source/conf.py
  
