services:
  - type: web
    name: vital-DSP
    env: python
    buildCommand: cd src && pip install -r ../requirements.txt && pip install -r vitalDSP_webapp/requirements.txt
    startCommand: cd src && python start.py
    healthCheckPath: /api/health
    envVars:
      - key: PYTHONPATH
        value: src
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONDONTWRITEBYTECODE
        value: 1