name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ./src  # Set PYTHONPATH to include the src directory

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8 pandoc pandas pytest-mock
          pip install setuptools wheel twine sphinx coveralls  

      - name: Run Tests
        run: make test

      - name: Generate Coverage Report
        run: pytest --cov=src --cov-config=.coveragerc --cov-report=html:cov_html


      - name: Run Linting
        run: make lint

      - name: Generate Documentation
        run: make pandoc

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: cov_html

      - name: Upload Documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: $(DOCS_DIR)
      
      - name: Build package
        run: make build
      
      - name: Send coverage to Coveralls
        run: coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      # - name: Deploy to PyPI
      #   if: github.ref == 'refs/heads/main'
      #   run: make upload
      #   env:
      #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}